### ISSUE TITLE
There is not types neither examples in Additional Attributes Section

### ISSUE THREAD

**Issue by dancespiele** [nevermined-io/docs#44]
## Description
In the section of the documentation of Metadata Additional Attributes there is not types neither examples to use as a reference in order to validate the payload

## Where
https://docs.nevermined.io/architecture/specs/metadata/#other-suggested-additional-attributes

## Acceptance criteria
Types and examples should be added for each parameter

## Effort
low

## Impact
medium

**Comment by aaitor** [comment]
`additionalAttributes` it's a flexible key, value storage that can be used freely by marketplaces
